title:            Autumn Moon's site
description:      Why are you here? -_-.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              //SaratBobbili.github.io
#http://localhost:5000
#https://jponttuset.github.io
disqus_shortname: sarat

# Owner/author information
owner:
  name:           Sarat Chandra Bobbili
  avatar:         Sarat.jpeg
  bio:            I'm from Kakinada, Andhra Pradesh. Currently in College Station, Texas. Current Passions include Photography, Archery, and Mountains.
  email:          saratbobbili@tamu.edu
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  #twitter: jponttuset
  linkedin: sarat-chandra-b-1ba5509a
  google_scholar: t_pK3k8AAAAJ
  #google_plus: 113718226018314522413
  github: SaratBobbili
# Analytics and webmaster tools stuff goes here
#google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
#bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Curriculum
    url: /cv/
  - title: Publications
    url: /publications/
  - title: Code
    url: /code/
  - title: Blog
    url: /blog/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    US/Central
future:      true
#pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]
  
# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

syntax_highlighter_opts:
  line_numbers:
  line_numbers_start: 1
  tab_width: 4
  bold_every: 10
  css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
